### ISSUE TITLE
It dosen't work for run_amp.py

### ISSUE THREAD

**Issue by xdzhang-xdu** [MJ10/BioSeq-GFN-AL#1]
The error is as follows.

/home/sunsun/xdzhang/BioSeq-GFN-AL-master/venv/bin/python /home/sunsun/xdzhang/BioSeq-GFN-AL-master/run_amp.py
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/home/sunsun/xdzhang/BioSeq-GFN-AL-master/run_amp.py", line 402, in <module>
    main(args)
  File "/home/sunsun/xdzhang/BioSeq-GFN-AL-master/run_amp.py", line 394, in main
    oracle = get_oracle(args)
  File "/home/sunsun/xdzhang/BioSeq-GFN-AL-master/lib/oracle_wrapper.py", line 9, in get_oracle
    return AMPOracleWrapper(args)
  File "/home/sunsun/xdzhang/BioSeq-GFN-AL-master/lib/oracle_wrapper.py", line 18, in __init__
    self.oracle = get_test_oracle(args.oracle_split, 
  File "/home/sunsun/xdzhang/clamp-gen-data-master/clamp_common_eval/defaults.py", line 51, in get_test_oracle
    return MLPOracle(source, feature)
  File "/home/sunsun/xdzhang/clamp-gen-data-master/clamp_common_eval/oracles/MLP.py", line 40, in __init__
    self.model.load_state_dict(torch.load(self.best_model_path, map_location=torch.device('cpu')))
  File "/home/sunsun/xdzhang/BioSeq-GFN-AL-master/venv/lib/python3.8/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/sunsun/xdzhang/BioSeq-GFN-AL-master/venv/lib/python3.8/site-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by phaphuang** [comment]
You need to use "git lfs clone".

**Comment by xdzhang-xdu** [comment]
> 
What difference will be brought? I tried, it didnt work.

**Comment by phaphuang** [comment]
You need to download the full size of .pkl files.

**Comment by xdzhang-xdu** [comment]
> clamp_common_eval

You mean for the project design-bench and clamp_common_eval?

**Comment by MJ10** [comment]
@xdzhang-xjtu Apologies for the late response. Could you please provide more details? I am unable to reproduce this issue.
