### ISSUE TITLE
It seems not working for this script.

### ISSUE THREAD

**Issue by xdzhang-xdu** [MJ10/BioSeq-GFN-AL#2]
Traceback (most recent call last):
  File "/home/sunsun/xdzhang/BioSeq-GFN-AL-master/run_gfp.py", line 369, in <module>
    main(args)
  File "/home/sunsun/xdzhang/BioSeq-GFN-AL-master/run_gfp.py", line 364, in main
    train(args, oracle, dataset)
  File "/home/sunsun/xdzhang/BioSeq-GFN-AL-master/run_gfp.py", line 340, in train
    proxy = construct_proxy(args, tokenizer, dataset=dataset)
  File "/home/sunsun/xdzhang/BioSeq-GFN-AL-master/run_gfp.py", line 300, in construct_proxy
    proxy = get_proxy_model(args, tokenizer)
  File "/home/sunsun/xdzhang/BioSeq-GFN-AL-master/lib/proxy/__init__.py", line 5, in get_proxy_model
    proxy = DropoutRegressor(args, tokenizer)
  File "/home/sunsun/xdzhang/BioSeq-GFN-AL-master/lib/proxy/regression.py", line 17, in __init__
    self.init_model()
  File "/home/sunsun/xdzhang/BioSeq-GFN-AL-master/lib/proxy/regression.py", line 35, in init_model
    self.model.to(self.args.device)
  File "/home/sunsun/xdzhang/BioSeq-GFN-AL-master/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DropoutRegressor' object has no attribute 'model'

**Comment by MJ10** [comment]
@xdzhang-xjtu apologies again for the late response, but I am not able to reproduce this issue. Would it be possible to provide more details about your environment? I am unable to reproduce this issue following the README on a clean environment.
