### ISSUE TITLE
running in Colab

### ISSUE THREAD

**Issue by erfanhamdi** [MJ10/BioSeq-GFN-AL#7]
Do you have any suggestion on how I can run it on colab? I am currently getting this error while running `run_amp.py` :
```
Traceback (most recent call last):
  File "run_amp.py", line 17, in <module>
    from lib.oracle_wrapper import get_oracle
  File "/content/drive/.shortcut-targets-by-id/1OJuMbwiWEwoAuUV13UWschS1lo8xwvQc/aptamer_generation/BioSeq-GFN-AL/lib/oracle_wrapper.py", line 3, in <module>
    from clamp_common_eval.defaults import get_test_oracle
  File "/content/drive/.shortcut-targets-by-id/1OJuMbwiWEwoAuUV13UWschS1lo8xwvQc/aptamer_generation/BioSeq-GFN-AL/clamp-gen-data/clamp_common_eval/defaults.py", line 12, in <module>
    from .oracles.proto_dist import MedioidDistanceOracle
  File "/content/drive/.shortcut-targets-by-id/1OJuMbwiWEwoAuUV13UWschS1lo8xwvQc/aptamer_generation/BioSeq-GFN-AL/clamp-gen-data/clamp_common_eval/oracles/proto_dist.py", line 123, in <module>
    class MedioidDistanceOracle(Oracle):
  File "/content/drive/.shortcut-targets-by-id/1OJuMbwiWEwoAuUV13UWschS1lo8xwvQc/aptamer_generation/BioSeq-GFN-AL/clamp-gen-data/clamp_common_eval/oracles/proto_dist.py", line 139, in MedioidDistanceOracle
    base_path=f"/dev/shm/{os.environ['USER']}/clamp/",
  File "/usr/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'USER'
```

**Comment by MJ10** [comment]
Apologies for the late response. You can fix this by adding  `%env USER=xyz` at the beginning of  your notebook. It doesn't really make a difference since that class is not used in the code

**Comment by W-OK-E** [comment]
@erfanhamdi Were you able to run the whole thing in Colab?
Can you please provide the steps that you took?
